export const LANGUAGE_LOADERS = {
	astro: () => import("@shikijs/langs/astro"),
	bash: () => import("@shikijs/langs/bash"),
	c: () => import("@shikijs/langs/c"),
	cmake: () => import("@shikijs/langs/cmake"),
	cpp: () => import("@shikijs/langs/cpp"),
	csharp: () => import("@shikijs/langs/csharp"),
	css: () => import("@shikijs/langs/css"),
	dart: () => import("@shikijs/langs/dart"),
	diff: () => import("@shikijs/langs/diff"),
	dockerfile: () => import("@shikijs/langs/dockerfile"),
	dotenv: () => import("@shikijs/langs/dotenv"),
	elixir: () => import("@shikijs/langs/elixir"),
	erlang: () => import("@shikijs/langs/erlang"),
	fsharp: () => import("@shikijs/langs/fsharp"),
	go: () => import("@shikijs/langs/go"),
	graphql: () => import("@shikijs/langs/graphql"),
	haskell: () => import("@shikijs/langs/haskell"),
	html: () => import("@shikijs/langs/html"),
	ini: () => import("@shikijs/langs/ini"),
	java: () => import("@shikijs/langs/java"),
	javascript: () => import("@shikijs/langs/javascript"),
	json: () => import("@shikijs/langs/json"),
	jsonc: () => import("@shikijs/langs/jsonc"),
	jsx: () => import("@shikijs/langs/jsx"),
	kotlin: () => import("@shikijs/langs/kotlin"),
	less: () => import("@shikijs/langs/less"),
	lua: () => import("@shikijs/langs/lua"),
	makefile: () => import("@shikijs/langs/makefile"),
	markdown: () => import("@shikijs/langs/markdown"),
	mdx: () => import("@shikijs/langs/mdx"),
	nix: () => import("@shikijs/langs/nix"),
	"objective-c": () => import("@shikijs/langs/objective-c"),
	php: () => import("@shikijs/langs/php"),
	prisma: () => import("@shikijs/langs/prisma"),
	properties: () => import("@shikijs/langs/properties"),
	protobuf: () => import("@shikijs/langs/protobuf"),
	python: () => import("@shikijs/langs/python"),
	ruby: () => import("@shikijs/langs/ruby"),
	rust: () => import("@shikijs/langs/rust"),
	scala: () => import("@shikijs/langs/scala"),
	scss: () => import("@shikijs/langs/scss"),
	solidity: () => import("@shikijs/langs/solidity"),
	sql: () => import("@shikijs/langs/sql"),
	svelte: () => import("@shikijs/langs/svelte"),
	swift: () => import("@shikijs/langs/swift"),
	terraform: () => import("@shikijs/langs/terraform"),
	toml: () => import("@shikijs/langs/toml"),
	tsx: () => import("@shikijs/langs/tsx"),
	typescript: () => import("@shikijs/langs/typescript"),
	vue: () => import("@shikijs/langs/vue"),
	xml: () => import("@shikijs/langs/xml"),
	yaml: () => import("@shikijs/langs/yaml"),
	zig: () => import("@shikijs/langs/zig"),
} as const;

export type SupportedLanguage = keyof typeof LANGUAGE_LOADERS;

const LANGUAGE_ALIASES: Record<string, SupportedLanguage> = {
	astro: "astro",
	bash: "bash",
	c: "c",
	"c++": "cpp",
	"c#": "csharp",
	cmake: "cmake",
	cpp: "cpp",
	cs: "csharp",
	csharp: "csharp",
	css: "css",
	dart: "dart",
	diff: "diff",
	docker: "dockerfile",
	dockerfile: "dockerfile",
	dotenv: "dotenv",
	elixir: "elixir",
	erlang: "erlang",
	fsharp: "fsharp",
	go: "go",
	gql: "graphql",
	graphql: "graphql",
	haskell: "haskell",
	html: "html",
	ini: "ini",
	java: "java",
	javascript: "javascript",
	js: "javascript",
	json: "json",
	json5: "jsonc",
	jsonc: "jsonc",
	jsx: "jsx",
	kotlin: "kotlin",
	less: "less",
	lua: "lua",
	make: "makefile",
	makefile: "makefile",
	markdown: "markdown",
	md: "markdown",
	mdx: "mdx",
	nix: "nix",
	objc: "objective-c",
	"objective-c": "objective-c",
	php: "php",
	prisma: "prisma",
	properties: "properties",
	proto: "protobuf",
	protobuf: "protobuf",
	py: "python",
	python: "python",
	rb: "ruby",
	ruby: "ruby",
	rs: "rust",
	rust: "rust",
	scala: "scala",
	scss: "scss",
	sh: "bash",
	shell: "bash",
	shellscript: "bash",
	sol: "solidity",
	solidity: "solidity",
	sql: "sql",
	svelte: "svelte",
	swift: "swift",
	terraform: "terraform",
	tf: "terraform",
	toml: "toml",
	ts: "typescript",
	tsx: "tsx",
	typescript: "typescript",
	vue: "vue",
	xml: "xml",
	yaml: "yaml",
	yml: "yaml",
	zig: "zig",
	zsh: "bash",
};

const FILE_NAME_LANGUAGES: Record<string, SupportedLanguage> = {
	"cmakelists.txt": "cmake",
	"compose.yaml": "yaml",
	"compose.yml": "yaml",
	"docker-compose.yaml": "yaml",
	"docker-compose.yml": "yaml",
	"gnumakefile": "makefile",
	"gnumakefile.am": "makefile",
	"gnumakefile.in": "makefile",
	"makefile": "makefile",
	"makefile.am": "makefile",
	"makefile.in": "makefile",
};

const EXTENSION_LANGUAGES: Record<string, SupportedLanguage> = {
	astro: "astro",
	bash: "bash",
	c: "c",
	cc: "cpp",
	cjs: "javascript",
	cmake: "cmake",
	cpp: "cpp",
	cs: "csharp",
	css: "css",
	cts: "typescript",
	cxx: "cpp",
	dart: "dart",
	diff: "diff",
	dockerfile: "dockerfile",
	ex: "elixir",
	exs: "elixir",
	fs: "fsharp",
	fsx: "fsharp",
	go: "go",
	gql: "graphql",
	graphql: "graphql",
	h: "c",
	hh: "cpp",
	hpp: "cpp",
	hrl: "erlang",
	hs: "haskell",
	htm: "html",
	html: "html",
	ini: "ini",
	java: "java",
	js: "javascript",
	json: "json",
	json5: "jsonc",
	jsonc: "jsonc",
	jsx: "jsx",
	kt: "kotlin",
	kts: "kotlin",
	less: "less",
	lua: "lua",
	md: "markdown",
	mdx: "mdx",
	mjs: "javascript",
	mts: "typescript",
	nix: "nix",
	patch: "diff",
	php: "php",
	prisma: "prisma",
	properties: "properties",
	proto: "protobuf",
	py: "python",
	pyi: "python",
	rb: "ruby",
	rs: "rust",
	scala: "scala",
	scss: "scss",
	sh: "bash",
	sol: "solidity",
	sql: "sql",
	svelte: "svelte",
	svg: "xml",
	swift: "swift",
	tf: "terraform",
	tfvars: "terraform",
	toml: "toml",
	ts: "typescript",
	tsx: "tsx",
	vue: "vue",
	xml: "xml",
	yaml: "yaml",
	yml: "yaml",
	zig: "zig",
	zsh: "bash",
};

export function resolveCodeLanguage(language?: string): SupportedLanguage | undefined {
	if (!language) return undefined;
	const normalized = language.trim().toLowerCase().replace(/^language-/, "");
	return LANGUAGE_ALIASES[normalized];
}

export function resolveFileLanguage(path: string): SupportedLanguage | undefined {
	const pathParts = path.split(/[\\/]/);
	const fileName = pathParts[pathParts.length - 1]?.toLowerCase();
	if (!fileName) return undefined;
	if (fileName === "dockerfile" || fileName.startsWith("dockerfile.")) return "dockerfile";
	if (fileName === ".env" || fileName.startsWith(".env.")) return "dotenv";
	if (fileName === ".bashrc" || fileName === ".zshrc") return "bash";
	const namedLanguage = FILE_NAME_LANGUAGES[fileName];
	if (namedLanguage) return namedLanguage;
	const fileNameParts = fileName.split(".");
	const extension = fileName.includes(".") ? fileNameParts[fileNameParts.length - 1] : undefined;
	return extension ? EXTENSION_LANGUAGES[extension] : undefined;
}
